// Generated by CoffeeScript 1.6.2
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.container = {
    load: function(appId) {
      var _this = this;

      return require({
        baseUrl: 'src'
      }, [appId + '/app.nocache'], (function(config) {
        return require({
          context: appId,
          baseUrl: 'src',
          paths: config.paths
        }, [config.entryPoint], _this.callback);
      }), this.error);
    },
    callback: function(App) {
      return console.log(App);
    },
    error: function() {
      throw "Can't load application";
    }
  };

}).call(this);
